# Catppuccin Mocha (dark)

set -g status-style          "bg=#1e1e2e,fg=#cdd6f4"
set -g message-style         "bg=#1e1e2e,fg=#f38ba8"
set -g message-command-style "bg=#1e1e2e,fg=#89b4fa"

set -g pane-border-style        "fg=#313244"
set -g pane-active-border-style "fg=#89b4fa"

set -g window-status-style          "fg=#6c7086"
set -g window-status-current-style  "fg=#89b4fa,bold"
set -g window-status-activity-style "fg=#f9e2af,bold"

set -g status-left  "#[bg=#89b4fa,fg=#1e1e2e,bold] #S #[bg=#1e1e2e,fg=#89b4fa]#{?client_prefix, #[fg=#f38ba8][^A]#[fg=#89b4fa],}#{?window_zoomed_flag, #[fg=#a6e3a1][Z]#[fg=#89b4fa],} "
set -g status-right "#(~/.config/zsh/scripts/tmux-sys-info.sh)#[fg=#6c7086]  %H:%M  %d %b "
